version: "3"

services:
  api:
    build:
      context: ./api
    ports:
      - "6000:6000"
    networks:
      - ntx-network

  etl:
    build:
      context: ./etl
    depends_on:
      - api
    networks:
      - ntx-network

networks:
  ntx-network:
